export const SECURITY_OPTIONS = Symbol('SECURITY_OPTIONS');

export const JWE_OPTIONS = Symbol('JWE_OPTIONS');
export const JWE_STORE = Symbol('JWE_STORE');

export const RATE_LIMIT_STORE = Symbol('RATE_LIMIT_STORE');
export const DEVICE_STORE = Symbol('DEVICE_STORE');
export const FINGERPRINT_SECRET = Symbol('FINGERPRINT_SECRET');

export const GEOIP_PROVIDER = Symbol('GEOIP_PROVIDER');
export const DEVICE_TRUST_TTL_SECONDS = Symbol('DEVICE_TRUST_TTL_SECONDS');

export const TENANT_VERIFICATION_OPTIONS = Symbol('TENANT_VERIFICATION_OPTIONS');
export const TENANT_GRPC_CLIENT = 'TENANT_GRPC_CLIENT';
