name: Build Package

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  

    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: ⚙️ Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11.24.0

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '26.8.1'
          cache: 'pnpm'

      - name: 📦 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 📦 build
        run: pnpm build
