name: Build Package

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  

    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: ⚙️ Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11.24.0

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '26.8.1'
          cache: 'pnpm'

      - name: Setup npm registry auth
        run: |
          echo "@omnixys:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${OMNIXYS_TOKEN}" >> .npmrc
        env:
          OMNIXYS_TOKEN: ${{ secrets.OMNIXYS_TOKEN }}

      - name: 📦 Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.OMNIXYS_TOKEN }}

      - name: 📦 build
        run: pnpm build
